### ISSUE TITLE
Issue w/ Creating New Google Doc (doc, sheets, or anything)

### ISSUE THREAD

**Issue by Jawwads** [azai91/alfred-drive-workflow#20]
@azai91, I usually get this notification when I try to create a new doc; 
![image](https://cloud.githubusercontent.com/assets/2739634/22269873/353965c4-e25b-11e6-8a77-2f68ae433f02.png)

Sometimes it works in creating the new doc and sometimes it gives me the above. Any idea what is going on?

**Comment by sorbits** [comment]
I had this happen as well and I had to re-run `d > login` to fix the issue.

I could still search and open documents because this was (presumably) using cached data.

**Comment by sorbits** [comment]
I looked at the code and the problem is that the access token does not get refreshed.

As a quick fix I inserted `cls.refresh()` just above [this line](https://github.com/azai91/alfred-drive-workflow/blob/master/src/drive_api.py#L263).

I say it is a “quick fix” because refreshing an access token should only be done when the access token has expired, so there is minor performance overhead by always refreshing it, and maybe Google will even throttle you, if you create thousands of new documents :)
