### ISSUE TITLE
PDFs taking precedence

### ISSUE THREAD

**Issue by jzadra** [azai91/alfred-drive-workflow#58]
Most of the time my search results are dominated by 10-20 PDF's that have very little relation to my search term, while way down in the results list will be a gdoc or gsheet that almost exactly matches the search query.

**Comment by sorbits** [comment]
The short answer is that proper filter and ranking really ought to be done by Alfred, but it currently does not offer a satisfying solution, and implementing it in the workflow is problematic both because Alfred does some re-ordering of results (based on last recently used) and because it would be very difficult to do proper learning (e.g. when you want `i` to match `Invoices` rather `Inventory`).

This was actually the straw that broke the camel’s back for me, and made me stop developing this workflow, and instead write a replacement for Alfred which improves on the shortcomings I discovered while rewriting this workflow.

It’s currently in private beta, if you would like an invite, let me know.

**Comment by jzadra** [comment]
Hi,

Yes I’d love to check it out.  This workflow was the entire reason I paid for Alfred.

Thanks,

Jon

On Apr 27, 2018, 8:01 PM -0600, Allan Odgaard <notifications@github.com>, wrote:
> The short answer is that proper filter and ranking really ought to be done by Alfred, but it currently does not offer a satisfying solution, and implementing it in the workflow is problematic both because Alfred does some re-ordering of results (based on last recently used) and because it would be very difficult to do proper learning (e.g. when you want i to match Invoices rather Inventory).
> This was actually the straw that broke the camel’s back for me, and made me stop developing this workflow, and instead write a replacement for Alfred which improves on the shortcomings I discovered while rewriting this workflow.
> It’s currently in private beta, if you would like an invite, let me know.
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

--

**Comment by sorbits** [comment]
> Yes I’d love to check it out.  This workflow was the entire reason I paid for Alfred.

I’ve invited you to a private repository from where you can download a beta.

Use “Authenticate Google Drive” to add your Google Drive items to the beta release. After this you have your Google Drive items at the root level (not hidden behind `d` as in Alfred) and there are also “New Document/Spreadsheet…” actions on the root level.

The cache is automatically refreshed when creating new documents, and otherwise after 10 minutes, but you can force a refresh with the “Clear Google Drive Cache” item.

P.S. Closing this issue, as I think it’s really an issue with Alfred.
